version: "3.5"

networks:
  app-network:
    name: app-network
    driver: bridge

services:
    nestjs:
        container_name: nestjs
        build:
            context: requirements/nestjs
            dockerfile: Dockerfile
        ports:
            - 3333:3333
        volumes:
            - ./requirements/nestjs/srcs:/srcs
        networks:
          - app-network

    postgresql:
        container_name: postgresql
        build:
            context: requirements/postgresql
            dockerfile: Dockerfile
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: nest
        networks:
          - app-network    
    react:
        container_name: react
        build: ./requirements/react
        restart: unless-stopped
        ports:
            - "3000:3000"
        networks:
          - app-network
