version: "3.8"
services:
    nodeserver:
        container_name: nodeserver
        build:
            context: ./app
        ports:
            - "5000:5000"
    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./nginx
        ports:
            - "3000:80"